const products = [
  {
    _id: "1",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "3",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "4",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "5",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "6",
    name: "The North Face Stormbreak 2 Tent",
    image: "/images/stormbreak-2-tent.png",
    description:
      "With large doors and 2 multi-configuration vestibules, The North Face Stormbreak 2 tent offers easy access and a great view of the great outdoors for 2 campers through 3 seasons.",
    brand: "The North Face",
    season: "3-season",
    capacity: "2-person",
    packed_weight: "5 lbs. 14.2 oz.",
    packed_size: "7 x 22 inches",
    floor_dimensions: "87 x 50 inches",
    peak_height: "43 inches",
    door_count: "2 doors",
    canopy_fabric: "75-denier polyester taffeta",
    floor_fabric: "68-denier polyester, 3000mm polyurethane coating",
    price: 159.99,
    countInStock: 10,
    rating: 2.5,
    numReviews: 12,
  },
];

export default products;
